[package]
name = "random-question"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.8.15", features = ["csr"] }
rand = "0.10.0"
getrandom = { version = "0.4", features = ["wasm_js"] }
